services:
  webserver:
    ports:
      - '${DOCKER_HTTPS_PORT:-443}:443'
    volumes:
      - .docker/nginx/vhost-ssl.conf:/etc/nginx/conf.d/default.conf
      - "${DOCKER_CERT_DIR:-.docker/certs}:/etc/nginx/ssl-certs"
